# syntax = docker/dockerfile:1
FROM node:20-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app
COPY . .
RUN rm -rf ./apps/@back
RUN rm -rf ./apps/@front
RUN rm -rf ./apps/@batch/broadcast

WORKDIR /app/apps/@batch/scrap
RUN pnpm install
RUN pnpm build

EXPOSE 8080

CMD ["pnpm", "start"]
