# syntax = docker/dockerfile:1
FROM node:18.18.2-slim as base

LABEL fly_launch_runtime="NestJS"

ENV NODE_ENV="production"
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app
COPY . /app/
RUN rm -rf /app/apps/@batch
RUN rm -rf /app/apps/@front

WORKDIR /app/apps/@back/server
RUN pnpm install
RUN pnpm build:prod

EXPOSE 8080

CMD ["pnpm", "start"]
