# syntax = docker/dockerfile:1
FROM node:18.18.2-slim as base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app
COPY . .
RUN rm -rf ./apps/@back
RUN rm -rf ./apps/@front
RUN rm -rf ./apps/@batch/scrap

WORKDIR /app/apps/@batch/broadcast
RUN pnpm install
RUN pnpm build:prod

EXPOSE 8080

CMD ["pnpm", "start"]
