name: Deploy @batch/scrap Production
on: workflow_dispatch

jobs:
  build-deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: .env.PROD setting
        working-directory: ./apps/@batch/scrap
        run: |
          touch .env.PROD
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.PROD
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.PROD
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env.PROD
          echo "SERVER_BASE_URL=${{ secrets.SERVER_BASE_URL }}" >> .env.PROD

      - name: setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Publish
        run: flyctl deploy --config apps/@batch/scrap/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      