name: Deploy @front/client Production
on: workflow_dispatch

jobs:
  build-deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: .env.PROD setting
        working-directory: ./apps/@front/client
        run: |
          touch .env.PROD
          echo "VITE_SERVER_DOMAIN=${{ secrets.VITE_SERVER_DOMAIN }}" >> .env.PROD
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env.PROD

      - name: build Prod
        working-directory: ./apps/@front/client
        run: pnpm build:prod

      - name: Publish
        working-directory: ./apps/@front/client
        run: pnpm --package=netlify-cli dlx netlify deploy --dir=./apps/@front/client/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      