name: Deploy @back/server Production
on: workflow_dispatch

jobs:
  build-deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: .env.PROD setting
        working-directory: ./apps/@back/server
        run: |
          touch .env.PROD
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.PROD
          echo "GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> .env.PROD
          echo "GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" >> .env.PROD
          echo "GOOGLE_OAUTH_REDIRECT_URI=${{ secrets.GOOGLE_OAUTH_REDIRECT_URI }}" >> .env.PROD
          echo "GOOGLE_OAUTH_JWT_SECRET=${{ secrets.GOOGLE_OAUTH_JWT_SECRET }}" >> .env.PROD
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.PROD
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.PROD
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env.PROD
          echo "CLIENT_DOMAIN=${{ secrets.CLIENT_DOMAIN }}" >> .env.PROD
          echo "ALLOW_ACCESS_ORIGIN=${{ secrets.ALLOW_ACCESS_ORIGIN }}" >> .env.PROD

      - name: setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Publish
        run: flyctl deploy --remote-only --config apps/@back/server/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      